"""Genera data/interim/pilot_questions.jsonl con las 20 preguntas piloto."""

import json
from collections import Counter
from pathlib import Path

questions = [
    # --- Q1 (existente) ---
    {
        "id": "laibe-0001",
        "version": "0.1.0",
        "question": "Una empresa procesa los datos personales de sus empleados para calcular y abonar sus nominas mensuales. Cual es la base juridica del RGPD aplicable en este supuesto?",
        "task_type": "MC",
        "options": {
            "A": "El consentimiento explicito de cada empleado",
            "B": "La ejecucion de un contrato del que el interesado es parte",
            "C": "El interes legitimo del empresario",
            "D": "La proteccion de intereses vitales del empleado",
        },
        "correct_option": "B",
        "gold_explanation": "El tratamiento se basa en el cumplimiento de un contrato laboral del que el empleado es parte (Art. 6.1.b) y, complementariamente, en una obligacion legal del empresario (Art. 6.1.c). El consentimiento no es valido en este contexto por la asimetria de poder.",
        "norm": "RGPD",
        "article_refs": ["Art. 6.1.b RGPD", "Art. 6.1.c RGPD"],
        "source_quote": "el tratamiento es necesario para la ejecucion de un contrato en el que el interesado es parte o para la aplicacion a peticion de este de medidas precontractuales",
        "bloom_level": "L3",
        "difficulty": "medium",
        "language": "es-ES",
        "created_by": "autor1",
        "created_at": "2026-06-15",
    },
    # --- Q2 (existente) ---
    {
        "id": "laibe-0002",
        "version": "0.1.0",
        "question": "Cual es el plazo maximo que establece el RGPD para notificar a la autoridad de control una violacion de la seguridad de los datos personales?",
        "task_type": "SHORT",
        "gold_answer": "72 horas",
        "aliases": ["72h", "setenta y dos horas", "72 horas naturales"],
        "gold_explanation": "El Art. 33.1 RGPD obliga al responsable a notificar a la autoridad de control sin dilacion indebida y, a mas tardar, 72 horas despues de tener constancia de la violacion.",
        "norm": "RGPD",
        "article_refs": ["Art. 33.1 RGPD"],
        "source_quote": "el responsable del tratamiento la notificara a la autoridad de control competente... sin dilacion indebida y, de ser posible, a mas tardar 72 horas despues de que haya tenido constancia de ella",
        "bloom_level": "L1",
        "difficulty": "easy",
        "language": "es-ES",
        "created_by": "autor1",
        "created_at": "2026-06-15",
    },
    # --- Q3 (existente) ---
    {
        "id": "laibe-0003",
        "version": "0.1.0",
        "question": "Segun el Reglamento de IA (UE) 2024/1689, cual de las siguientes practicas esta expresamente prohibida y no puede comercializarse en la Union Europea?",
        "task_type": "MC",
        "options": {
            "A": "Sistemas de IA que evaluan a estudiantes en examenes finales",
            "B": "Sistemas de IA que generan deepfakes con fines artisticos",
            "C": "Sistemas de IA que clasifican a las personas en funcion de su comportamiento social produciendo un trato perjudicial injustificado",
            "D": "Sistemas de IA usados por bancos para evaluar la solvencia crediticia",
        },
        "correct_option": "C",
        "gold_explanation": "El Art. 5.1.c del Reglamento (UE) 2024/1689 prohibe los sistemas de social scoring que conducen a un trato perjudicial en contextos sociales no relacionados o desproporcionado. Las otras opciones describen sistemas de alto riesgo (A, D) o de riesgo limitado con obligaciones de transparencia (B), pero no prohibidos.",
        "norm": "AI_ACT",
        "article_refs": ["Art. 5.1.c AI Act"],
        "source_quote": "la puesta en servicio o utilizacion de sistemas de IA para evaluar o clasificar a personas fisicas... atendiendo a su comportamiento social o a caracteristicas personales o de la personalidad conocidas, inferidas o predichas, de forma que la puntuacion ciudadana resultante provoque... un trato perjudicial o desfavorable",
        "bloom_level": "L2",
        "difficulty": "medium",
        "language": "es-ES",
        "created_by": "autor1",
        "created_at": "2026-06-15",
    },
    # --- Q4: RGPD SHORT L1 ---
    {
        "id": "laibe-0004",
        "version": "0.1.0",
        "question": "¿Cómo denomina el RGPD al principio que exige que los datos personales sean recogidos con fines determinados, explícitos y legítimos, y no sean tratados ulteriormente de manera incompatible con dichos fines?",
        "task_type": "SHORT",
        "gold_answer": "limitación de la finalidad",
        "aliases": [
            "limitacion de la finalidad",
            "limitación de finalidad",
            "principio de limitación de finalidad",
        ],
        "gold_explanation": "El Art. 5.1.b RGPD establece el principio de limitación de la finalidad: los datos deben recogerse con fines determinados, explícitos y legítimos y no tratarse de forma incompatible. Se distingue de minimización (5.1.c), exactitud (5.1.d) y limitación de conservación (5.1.e).",
        "norm": "RGPD",
        "article_refs": ["Art. 5.1.b RGPD"],
        "source_quote": "recogidos con fines determinados, explícitos y legítimos, y no serán tratados ulteriormente de manera incompatible con dichos fines",
        "bloom_level": "L1",
        "difficulty": "easy",
        "language": "es-ES",
        "created_by": "autor1",
        "created_at": "2026-05-27",
    },
    # --- Q5: RGPD MC L2 ---
    {
        "id": "laibe-0005",
        "version": "0.1.0",
        "question": "Un responsable del tratamiento desea procesar datos de salud de sus pacientes para ofrecerles diagnósticos preventivos personalizados. Los pacientes han prestado su consentimiento explícito a este tratamiento concreto. ¿Bajo qué excepción del Art. 9.2 RGPD es lícito este tratamiento?",
        "task_type": "MC",
        "options": {
            "A": "Los intereses vitales del interesado cuando este no esté en condiciones de prestar su consentimiento",
            "B": "El interés legítimo del responsable en prestar un servicio de salud de calidad",
            "C": "La ejecución de un contrato de servicios del que el interesado es parte",
            "D": "El consentimiento explícito del interesado para uno o varios fines específicos",
        },
        "correct_option": "D",
        "gold_explanation": "El Art. 9.2.a RGPD permite el tratamiento de categorías especiales cuando el interesado presta consentimiento explícito para fines específicos. El interés legítimo no es excepción válida en Art. 9.2; la ejecución de contrato aplica a Art. 6.1.b, no a categorías especiales; los intereses vitales solo operan cuando el interesado no puede consentir.",
        "norm": "RGPD",
        "article_refs": ["Art. 9.2.a RGPD"],
        "source_quote": "el interesado dio su consentimiento explícito para el tratamiento de dichos datos personales con uno o más de los fines especificados, excepto cuando el Derecho de la Unión o de los Estados miembros establezca que la prohibición mencionada en el apartado 1 no puede ser levantada por el interesado",
        "bloom_level": "L2",
        "difficulty": "medium",
        "language": "es-ES",
        "created_by": "autor1",
        "created_at": "2026-05-27",
    },
    # --- Q6: RGPD SHORT L1 ---
    {
        "id": "laibe-0006",
        "version": "0.1.0",
        "question": "¿Cuál es el plazo máximo ordinario que establece el RGPD para que el responsable del tratamiento responda a una solicitud de ejercicio de derechos por parte del interesado?",
        "task_type": "SHORT",
        "gold_answer": "un mes",
        "aliases": ["1 mes", "un mes natural", "30 días"],
        "gold_explanation": "El Art. 12.3 RGPD establece que el responsable facilitará la información dentro de un mes a partir de la recepción de la solicitud. Este plazo puede prorrogarse dos meses adicionales en casos de especial complejidad, pero el plazo ordinario es de un mes.",
        "norm": "RGPD",
        "article_refs": ["Art. 12.3 RGPD"],
        "source_quote": "el responsable del tratamiento facilitará al interesado información sobre las actuaciones realizadas en virtud de los artículos 15 a 22 dentro de un mes a partir de la recepción de la solicitud",
        "bloom_level": "L1",
        "difficulty": "easy",
        "language": "es-ES",
        "created_by": "autor1",
        "created_at": "2026-05-27",
    },
    # --- Q7: RGPD MC L3 ---
    {
        "id": "laibe-0007",
        "version": "0.1.0",
        "question": "Una entidad financiera implanta un sistema de puntuación de solvencia crediticia que evalúa automáticamente el perfil de riesgo de los solicitantes de préstamo a partir de su historial financiero, tomando decisiones vinculantes sobre la concesión del crédito. ¿Está obligada a realizar una evaluación de impacto relativa a la protección de datos (EIPD)?",
        "task_type": "MC",
        "options": {
            "A": "Sí, porque el tratamiento consiste en una evaluación sistemática de aspectos personales mediante tratamiento automatizado sobre cuya base se toman decisiones con efectos significativos",
            "B": "No, si la entidad cuenta con la aprobación del supervisor financiero para usar el sistema",
            "C": "No, porque el tratamiento persigue una finalidad contractual legítima y dispone de base jurídica en el Art. 6.1.b RGPD",
            "D": "Solo si el sistema utiliza categorías especiales de datos del Art. 9 RGPD",
        },
        "correct_option": "A",
        "gold_explanation": "El Art. 35.3.a RGPD hace obligatoria la EIPD cuando el tratamiento consiste en una evaluación sistemática de aspectos personales basada en tratamiento automatizado sobre cuya base se toman decisiones con efectos jurídicos o que afectan significativamente al interesado. La aprobación supervisora y la existencia de base jurídica no eximen de la EIPD.",
        "norm": "RGPD",
        "article_refs": ["Art. 35.3.a RGPD"],
        "source_quote": "evaluación sistemática y exhaustiva de aspectos personales de personas físicas que se base en un tratamiento automatizado, como la elaboración de perfiles, y sobre cuya base se tomen decisiones que produzcan efectos jurídicos para las personas físicas o que les afecten de manera igualmente significativa",
        "bloom_level": "L3",
        "difficulty": "hard",
        "language": "es-ES",
        "created_by": "autor1",
        "created_at": "2026-05-27",
    },
    # --- Q8: RGPD MC L2 ---
    {
        "id": "laibe-0008",
        "version": "0.1.0",
        "question": "¿En cuál de los siguientes supuestos reconoce el RGPD al interesado el derecho a solicitar la supresión de sus datos personales?",
        "task_type": "MC",
        "options": {
            "A": "Cuando los datos personales ya no sean necesarios en relación con los fines para los que fueron recogidos o tratados",
            "B": "Cuando el responsable del tratamiento sea una entidad del sector público",
            "C": "Cuando hayan transcurrido más de cinco años desde la recogida de los datos",
            "D": "Cuando el interesado no haya ejercido ningún otro derecho previamente",
        },
        "correct_option": "A",
        "gold_explanation": "El Art. 17.1.a RGPD establece el derecho de supresión cuando los datos ya no son necesarios para los fines que motivaron su recogida. Los demás supuestos (naturaleza pública del responsable, plazo de cinco años, ejercicio previo de otros derechos) no figuran en el Art. 17.1 RGPD.",
        "norm": "RGPD",
        "article_refs": ["Art. 17.1.a RGPD"],
        "source_quote": "los datos personales ya no sean necesarios en relación con los fines para los que fueron recogidos o tratados de otro modo",
        "bloom_level": "L2",
        "difficulty": "medium",
        "language": "es-ES",
        "created_by": "autor1",
        "created_at": "2026-05-27",
    },
    # --- Q9: RGPD MC L1 ---
    {
        "id": "laibe-0009",
        "version": "0.1.0",
        "question": "Según el RGPD, ¿cuál de las siguientes descripciones corresponde a la definición de «datos biométricos»?",
        "task_type": "MC",
        "options": {
            "A": "Datos relativos a la salud del interesado, incluidos historiales clínicos y diagnósticos médicos",
            "B": "Datos obtenidos mediante encuestas de bienestar que revelan el estado físico habitual del individuo",
            "C": "Datos de geolocalización que permiten reconstruir los desplazamientos de una persona a lo largo del tiempo",
            "D": "Datos personales obtenidos a partir de un tratamiento técnico específico relativos a las características físicas, fisiológicas o conductuales de una persona que permiten o confirman su identificación única",
        },
        "correct_option": "D",
        "gold_explanation": "El Art. 4.14 RGPD define los datos biométricos como los obtenidos a partir de un tratamiento técnico específico, relativos a características físicas, fisiológicas o conductuales que permiten o confirman la identificación única de la persona. Los datos de salud, bienestar y localización son categorías distintas.",
        "norm": "RGPD",
        "article_refs": ["Art. 4.14 RGPD"],
        "source_quote": "datos personales obtenidos a partir de un tratamiento técnico específico, relativos a las características físicas, fisiológicas o conductuales de una persona física que permitan o confirmen la identificación única de dicha persona",
        "bloom_level": "L1",
        "difficulty": "easy",
        "language": "es-ES",
        "created_by": "autor1",
        "created_at": "2026-05-27",
    },
    # --- Q10: RGPD MC L3 ---
    {
        "id": "laibe-0010",
        "version": "0.1.0",
        "question": "Una empresa española contrata a un proveedor de servicios en la nube establecido en un país tercero sin decisión de adecuación y sin garantías adecuadas mediante cláusulas contractuales tipo. La transferencia de datos de clientes es imprescindible para ejecutar el contrato suscrito directamente con esos clientes. ¿Qué excepción del Art. 49 RGPD legitima esta transferencia?",
        "task_type": "MC",
        "options": {
            "A": "El interés legítimo del responsable en externalizar servicios tecnológicos de forma eficiente",
            "B": "La necesidad de la transferencia para la ejecución de un contrato entre el interesado y el responsable",
            "C": "El interés público en fomentar el comercio exterior y la economía digital",
            "D": "La notificación previa y detallada a la autoridad de control competente",
        },
        "correct_option": "B",
        "gold_explanation": "El Art. 49.1.b RGPD permite la transferencia internacional sin garantías adecuadas cuando es necesaria para ejecutar un contrato entre el interesado y el responsable. El interés legítimo no figura como excepción en Art. 49.1. La notificación previa y el interés público no son bases de transferencia en este artículo.",
        "norm": "RGPD",
        "article_refs": ["Art. 49.1.b RGPD"],
        "source_quote": "la transferencia sea necesaria para la ejecución de un contrato entre el interesado y el responsable del tratamiento o para la ejecución de medidas precontractuales adoptadas a solicitud del interesado",
        "bloom_level": "L3",
        "difficulty": "hard",
        "language": "es-ES",
        "created_by": "autor1",
        "created_at": "2026-05-27",
    },
    # --- Q11: AI_ACT MC L1 ---
    {
        "id": "laibe-0011",
        "version": "0.1.0",
        "question": "Según el Reglamento (UE) 2024/1689, ¿cuál de las siguientes descripciones corresponde al concepto de «sistema de IA»?",
        "task_type": "MC",
        "options": {
            "A": "Cualquier software desarrollado mediante lenguajes de programación orientados a objetos que procesa datos para producir una salida",
            "B": "Cualquier algoritmo estadístico aplicado a conjuntos de datos de gran volumen para detectar patrones",
            "C": "Todo sistema de automatización de procesos robóticos que ejecuta secuencias de instrucciones predefinidas sin desviación posible",
            "D": "Un sistema basado en máquinas diseñado para funcionar con distintos niveles de autonomía que infiere, a partir de las entradas que recibe, cómo generar resultados tales como predicciones, recomendaciones o decisiones",
        },
        "correct_option": "D",
        "gold_explanation": "El Art. 3.1 del AI Act define el sistema de IA como un sistema basado en máquinas con distintos niveles de autonomía que infiere a partir de las entradas cómo generar resultados que influyan en entornos reales o virtuales. Los RPA que ejecutan instrucciones predefinidas sin inferencia no son sistemas de IA bajo esta definición.",
        "norm": "AI_ACT",
        "article_refs": ["Art. 3.1 AI Act"],
        "source_quote": "sistema basado en máquinas diseñado para funcionar con distintos niveles de autonomía, que puede mostrar capacidad de adaptación tras su despliegue y que, para objetivos explícitos o implícitos, infiere, a partir de las entradas que recibe, cómo generar resultados tales como predicciones, recomendaciones, decisiones u otros resultados",
        "bloom_level": "L1",
        "difficulty": "easy",
        "language": "es-ES",
        "created_by": "autor1",
        "created_at": "2026-05-27",
    },
    # --- Q12: AI_ACT MC L2 ---
    {
        "id": "laibe-0012",
        "version": "0.1.0",
        "question": "Un servicio de atención al cliente utiliza un chatbot de IA que mantiene conversaciones en tiempo real con usuarios a través de texto. Según el Art. 50 del Reglamento (UE) 2024/1689, ¿cuál es la obligación de transparencia que impone el Reglamento al responsable del despliegue?",
        "task_type": "MC",
        "options": {
            "A": "Informar a las personas con las que interactúa de que están hablando con un sistema de IA, salvo que ello sea evidente",
            "B": "Publicar en su web la documentación técnica completa del sistema de chatbot utilizado",
            "C": "Solicitar el consentimiento explícito de cada usuario antes de iniciar cualquier conversación automatizada",
            "D": "Registrar el sistema ante la Oficina Europea de Inteligencia Artificial antes de su puesta en servicio",
        },
        "correct_option": "A",
        "gold_explanation": "El Art. 50.1 del AI Act obliga a los responsables del despliegue de sistemas de IA que interactúan directamente con personas a informarles de que están interactuando con un sistema de IA, salvo que sea evidente. No existe obligación de publicar documentación técnica al público general, de recabar consentimiento previo ni de registrar el sistema para esta categoría.",
        "norm": "AI_ACT",
        "article_refs": ["Art. 50.1 AI Act"],
        "source_quote": "los responsables del despliegue de sistemas de IA destinados a interactuar directamente con personas físicas velarán por que las personas físicas sean informadas de que están interactuando con un sistema de IA, a menos que esto sea evidente habida cuenta de las circunstancias y del contexto de uso",
        "bloom_level": "L2",
        "difficulty": "medium",
        "language": "es-ES",
        "created_by": "autor1",
        "created_at": "2026-05-27",
    },
    # --- Q13: AI_ACT SHORT L1 ---
    {
        "id": "laibe-0013",
        "version": "0.1.0",
        "question": "Según el Art. 99 del Reglamento (UE) 2024/1689, ¿cuál es el porcentaje máximo del volumen de negocios mundial anual de una empresa que puede alcanzar la multa administrativa por infringir las prácticas de IA expresamente prohibidas en el Art. 5?",
        "task_type": "SHORT",
        "gold_answer": "7%",
        "aliases": ["7 %", "siete por ciento", "7 por ciento"],
        "gold_explanation": "El Art. 99.3 del AI Act fija para las infracciones de las prohibiciones del Art. 5 multas de hasta 35.000.000 EUR o, si el infractor es una empresa, de hasta el 7 % de su volumen de negocios mundial total anual del ejercicio financiero anterior, si esta cifra fuese superior.",
        "norm": "AI_ACT",
        "article_refs": ["Art. 99.3 AI Act"],
        "source_quote": "multas administrativas de hasta 35 000 000 EUR o, si el infractor es una empresa, de hasta el 7 % de su volumen de negocios mundial total anual del ejercicio financiero anterior",
        "bloom_level": "L1",
        "difficulty": "easy",
        "language": "es-ES",
        "created_by": "autor1",
        "created_at": "2026-05-27",
    },
    # --- Q14: AI_ACT MC L3 ---
    {
        "id": "laibe-0014",
        "version": "0.1.0",
        "question": "Una empresa de recursos humanos despliega un sistema de IA de alto riesgo para la preselección de candidatos adquirido a un proveedor externo. Durante su uso detecta que el sistema genera sesgos sistemáticos que perjudican a determinados colectivos, representando un riesgo grave para los derechos fundamentales de los candidatos. ¿Cuál es la obligación principal del responsable del despliegue conforme al Reglamento (UE) 2024/1689?",
        "task_type": "MC",
        "options": {
            "A": "Continuar utilizando el sistema hasta que el proveedor emita una actualización oficial que corrija el sesgo",
            "B": "Aplicar medidas correctoras internas de forma autónoma sin necesidad de comunicar el incidente al proveedor ni a las autoridades",
            "C": "Notificar el incidente al proveedor y, si el riesgo es grave, suspender el uso del sistema e informar a las autoridades de vigilancia del mercado competentes",
            "D": "Transferir la responsabilidad jurídica del incidente al proveedor mediante notificación escrita fehaciente",
        },
        "correct_option": "C",
        "gold_explanation": "El Art. 26.5 del AI Act obliga al responsable del despliegue a informar al proveedor y a las autoridades de vigilancia del mercado de cualquier incidente grave. La opción A vulnera la diligencia debida; la B omite la notificación obligatoria; la D no existe como mecanismo de transferencia de responsabilidad en el Reglamento.",
        "norm": "AI_ACT",
        "article_refs": ["Art. 26.5 AI Act"],
        "source_quote": "los responsables del despliegue informarán al proveedor o al distribuidor correspondiente, así como a las autoridades de vigilancia del mercado pertinentes, de cualquier incidente grave",
        "bloom_level": "L3",
        "difficulty": "hard",
        "language": "es-ES",
        "created_by": "autor1",
        "created_at": "2026-05-27",
    },
    # --- Q15: AI_ACT MC L2 ---
    {
        "id": "laibe-0015",
        "version": "0.1.0",
        "question": "Según el Art. 51 del Reglamento (UE) 2024/1689, ¿cuándo se presume que un modelo de IA de uso general presenta riesgo sistémico?",
        "task_type": "MC",
        "options": {
            "A": "Cuando el modelo se utiliza para aplicaciones de infraestructura crítica o seguridad pública en al menos un Estado miembro",
            "B": "Cuando el modelo es accesible al público de forma gratuita a través de una API abierta sin restricciones",
            "C": "Cuando el modelo ha sido desplegado simultáneamente en más de cinco Estados miembros de la Unión Europea",
            "D": "Cuando la capacidad acumulada de cómputo utilizada para su entrenamiento supera los 10^25 operaciones en coma flotante",
        },
        "correct_option": "D",
        "gold_explanation": "El Art. 51.1.a del AI Act establece la presunción de riesgo sistémico cuando la capacidad acumulada de cómputo usada para entrenar el modelo supera los 10^25 FLOPs. El uso en infraestructuras críticas, la disponibilidad por API abierta y el número de Estados miembros no son los criterios de presunción de este artículo.",
        "norm": "AI_ACT",
        "article_refs": ["Art. 51.1.a AI Act"],
        "source_quote": "la capacidad acumulada de cómputo utilizada para entrenarlo supera los 10^25 operaciones en coma flotante",
        "bloom_level": "L2",
        "difficulty": "medium",
        "language": "es-ES",
        "created_by": "autor1",
        "created_at": "2026-05-27",
    },
    # --- Q16: AI_ACT MC L2 ---
    {
        "id": "laibe-0016",
        "version": "0.1.0",
        "question": "El Reglamento (UE) 2024/1689 clasifica ciertos sistemas de IA como de alto riesgo por estar destinados a ámbitos sensibles. ¿Cuál de los siguientes sistemas figura expresamente en el Anexo III del Reglamento como de alto riesgo?",
        "task_type": "MC",
        "options": {
            "A": "Sistemas de IA utilizados para el reclutamiento o la selección de candidatos para el empleo, incluidos el filtrado de solicitudes y la evaluación de candidatos",
            "B": "Sistemas de IA que generan contenido creativo como imágenes, música o texto literario por encargo del usuario",
            "C": "Sistemas de IA empleados para recomendar productos o contenidos personalizados en plataformas de comercio electrónico",
            "D": "Sistemas de IA utilizados para la traducción automática de documentos entre lenguas oficiales de la UE",
        },
        "correct_option": "A",
        "gold_explanation": "El Anexo III del AI Act incluye en su punto 4 los sistemas de IA para reclutamiento o selección de personas físicas (publicar ofertas de empleo, filtrar solicitudes, evaluar candidatos) como de alto riesgo. La generación de contenido creativo, las recomendaciones de productos y la traducción automática no figuran en el Anexo III.",
        "norm": "AI_ACT",
        "article_refs": ["Art. 6.2 AI Act"],
        "source_quote": "sistemas de IA destinados a ser utilizados para el reclutamiento o la selección de personas físicas, en particular para publicar ofertas de empleo específicas, examinar o filtrar solicitudes y evaluar a los candidatos",
        "bloom_level": "L2",
        "difficulty": "medium",
        "language": "es-ES",
        "created_by": "autor1",
        "created_at": "2026-05-27",
    },
    # --- Q17: AI_ACT MC L3 ---
    {
        "id": "laibe-0017",
        "version": "0.1.0",
        "question": "Un proveedor de un sistema de IA de alto riesgo ya comercializado detecta que el sistema no cumple con el requisito de transparencia del Art. 13 del Reglamento (UE) 2024/1689. ¿Cuál de las siguientes acciones está obligado a emprender de forma inmediata conforme al Art. 20?",
        "task_type": "MC",
        "options": {
            "A": "Retirar el sistema del mercado de forma definitiva e iniciar un nuevo proceso de certificación de conformidad",
            "B": "Esperar a que la autoridad nacional de vigilancia del mercado inicie formalmente una investigación antes de adoptar medidas",
            "C": "Publicar una declaración pública sobre la no conformidad y actualizar el manual de instrucciones para el usuario",
            "D": "Adoptar las medidas correctoras necesarias para restablecer la conformidad e informar de ello a los distribuidores y responsables del despliegue",
        },
        "correct_option": "D",
        "gold_explanation": "El Art. 20.1 del AI Act obliga al proveedor que detecta no conformidad a adoptar inmediatamente las medidas correctoras para restablecer la conformidad o, si no es posible, a retirar o recuperar el sistema, informando a los distribuidores y responsables del despliegue. No existe obligación de retirar definitivamente sin intentar la corrección ni de esperar a la autoridad supervisora.",
        "norm": "AI_ACT",
        "article_refs": ["Art. 20.1 AI Act"],
        "source_quote": "los proveedores de sistemas de IA de alto riesgo que consideren o tengan razones para considerar que un sistema de IA que han introducido en el mercado o puesto en servicio no es conforme con el presente Reglamento adoptarán inmediatamente las medidas correctoras necesarias para que el sistema sea conforme, para retirarlo o para recuperarlo",
        "bloom_level": "L3",
        "difficulty": "hard",
        "language": "es-ES",
        "created_by": "autor1",
        "created_at": "2026-05-27",
    },
    # --- Q18: AIACT_RGPD MC L2 ---
    {
        "id": "laibe-0018",
        "version": "0.1.0",
        "question": "Una empresa despliega un sistema de IA de alto riesgo que procesa datos personales de ciudadanos a gran escala para tomar decisiones automatizadas con efectos significativos en el acceso a servicios públicos. ¿Qué instrumentos de ambas normativas resultan aplicables de forma acumulativa?",
        "task_type": "MC",
        "options": {
            "A": "La evaluación de impacto relativa a la protección de datos del RGPD y el sistema de gestión de riesgos del Art. 9 del AI Act",
            "B": "Solo la EIPD del RGPD, porque el AI Act remite al RGPD cuando hay datos personales implicados",
            "C": "Solo el sistema de gestión de riesgos del AI Act, que desplaza al RGPD en el ámbito de la inteligencia artificial",
            "D": "El marcado CE del AI Act y la inscripción en el Registro de Actividades del RGPD, excluyendo la EIPD y la gestión de riesgos",
        },
        "correct_option": "A",
        "gold_explanation": "El AI Act y el RGPD son acumulativos: un sistema de IA de alto riesgo que procesa datos personales debe cumplir simultáneamente el Art. 9 AI Act (sistema de gestión de riesgos) y el Art. 35 RGPD (EIPD, por el alto riesgo para derechos fundamentales). Ninguna normativa desplaza a la otra.",
        "norm": "AIACT_RGPD",
        "article_refs": ["Art. 35.1 RGPD", "Art. 9.1 AI Act"],
        "source_quote": "cuando sea probable que un tipo de tratamiento, en particular si utiliza nuevas tecnologías, por su naturaleza, alcance, contexto o fines, entrañe un alto riesgo para los derechos y libertades de las personas físicas, el responsable del tratamiento realizará, antes del tratamiento, una evaluación del impacto",
        "bloom_level": "L2",
        "difficulty": "medium",
        "language": "es-ES",
        "created_by": "autor1",
        "created_at": "2026-05-27",
    },
    # --- Q19: AIACT_RGPD MC L3 ---
    {
        "id": "laibe-0019",
        "version": "0.1.0",
        "question": "Una startup participa en un sandbox regulatorio de IA establecido conforme al Art. 57 del Reglamento (UE) 2024/1689 y necesita utilizar datos personales reales de usuarios para entrenar y probar su modelo. ¿Bajo qué condición permite el Art. 59 del Reglamento este tratamiento de datos personales?",
        "task_type": "MC",
        "options": {
            "A": "Basta con que los interesados hayan prestado un consentimiento genérico a participar en programas de innovación tecnológica",
            "B": "El tratamiento es lícito si se sustenta en una base jurídica válida conforme al RGPD y los datos se tratan con las medidas de protección adecuadas dentro del entorno del sandbox",
            "C": "El sandbox crea un régimen jurídico autónomo que suspende la aplicación del RGPD durante el período de pruebas",
            "D": "La empresa debe anonimizar todos los datos antes de introducirlos en el sandbox, con independencia del objetivo del tratamiento",
        },
        "correct_option": "B",
        "gold_explanation": "El Art. 59 del AI Act establece que el tratamiento de datos personales en los sandbox regulatorios se realizará de conformidad con el Derecho de la Unión en materia de protección de datos. El sandbox no suspende el RGPD ni autoriza tratamientos sin base jurídica. El consentimiento genérico no satisface el requisito de especificidad. La anonimización no es obligatoria si existe base jurídica adecuada.",
        "norm": "AIACT_RGPD",
        "article_refs": ["Art. 59.1 AI Act"],
        "source_quote": "el tratamiento de datos personales en los sandbox regulatorios de IA a los efectos del presente artículo se efectuará de conformidad con el Derecho de la Unión aplicable en materia de protección de datos personales",
        "bloom_level": "L3",
        "difficulty": "hard",
        "language": "es-ES",
        "created_by": "autor1",
        "created_at": "2026-05-27",
    },
    # --- Q20: RGPD MC L2 ---
    {
        "id": "laibe-0020",
        "version": "0.1.0",
        "question": "Cuando un responsable del tratamiento encarga a un tercero el tratamiento de datos personales, el RGPD exige que la relación se formalice mediante contrato. ¿Cuál de los siguientes elementos es obligatorio que figure en ese contrato conforme al Art. 28.3 RGPD?",
        "task_type": "MC",
        "options": {
            "A": "La remuneración pactada entre responsable y encargado por los servicios prestados",
            "B": "La acreditación del encargado conforme a la norma ISO 27001 o a un esquema de certificación reconocido por el Art. 42 RGPD",
            "C": "La materia, duración, naturaleza y finalidad del tratamiento, el tipo de datos y las categorías de interesados, así como las obligaciones y derechos del responsable",
            "D": "La lista exhaustiva de todos los subencargados que el encargado prevé contratar durante la vigencia del contrato",
        },
        "correct_option": "C",
        "gold_explanation": "El Art. 28.3 RGPD exige que el contrato estipule la materia, duración, naturaleza y finalidad del tratamiento, el tipo de datos y las categorías de interesados, y las obligaciones y derechos del responsable. La remuneración, la certificación ISO y la lista exhaustiva de subencargados no son elementos exigidos por este artículo.",
        "norm": "RGPD",
        "article_refs": ["Art. 28.3 RGPD"],
        "source_quote": "el contrato u otro acto jurídico estipulará la materia, la duración, la naturaleza y la finalidad del tratamiento, el tipo de datos personales y las categorías de interesados, y las obligaciones y derechos del responsable del tratamiento",
        "bloom_level": "L2",
        "difficulty": "medium",
        "language": "es-ES",
        "created_by": "autor1",
        "created_at": "2026-05-27",
    },
]

out = Path("data/interim/pilot_questions.jsonl")
out.parent.mkdir(parents=True, exist_ok=True)
with out.open("w", encoding="utf-8") as f:
    for q in questions:
        f.write(json.dumps(q, ensure_ascii=False) + "\n")

print(f"OK {len(questions)} preguntas escritas en {out}")

# Resumen de distribución
types = Counter(q["task_type"] for q in questions)
blooms = Counter(q["bloom_level"] for q in questions)
norms = Counter(q["norm"] for q in questions)
options = Counter(q.get("correct_option") for q in questions if q["task_type"] == "MC")
print(f"  Tipo:  {dict(types)}")
print(f"  Bloom: {dict(blooms)}")
print(f"  Norma: {dict(norms)}")
print(f"  Opción correcta MC: {dict(sorted(options.items()))}")
